name: outputs-demo
on:
  workflow_dispatch


jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test1 }}
      output2: ${{ steps.step2.outputs.test2 }}
    steps:
      - id: step1
        run: echo "::set-output name=test1::hello"
      - id: step2
        run: echo "::set-output name=test2::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
       - run: echo ${{needs.job1.outptus.output1 }} ${{needs.job1.outptus.output2 }}
